[package]
name = "vietphys"
version = "0.1.0"
entrypoint = "vietphys.typ"
authors = ["Chung Diệu Minh"]
license = "MIT"
description = "Create Vietnamese physics lessons and question sheets."
compiler = "0.15.1"
exclude = ["/examples/", "/sbt-vat-li-10/", "/tests/", "/scripts/", "/dist/", "/.github/", "/.typst-packages/", "/.git/", "/.gitignore", "/.gitattributes"]
