#import "../vietphys.typ": *
#set page(paper: "a4", margin: (x: 60pt, y: 70pt))
#set text(font: "Arial")
#set page(header: vp-header-theme-01())
= Header 01
#vp-part("Running part")
#vp-widget-stack(vp-widget-author(), vp-widget-school())
#vp-widget-stack(vp-widget-date(), vp-widget-exam(), vp-widget-target())
#vp-widget-heading()
#vp-widget-smart-heading()
#vp-widget-part()
#pagebreak()
#set page(header: vp-header-theme-02())
= Header 02
#vp-part("Running part")
#vp-widget-stack(vp-widget-author(), vp-widget-school())
#vp-widget-stack(vp-widget-date(), vp-widget-exam(), vp-widget-target())
#vp-widget-heading()
#vp-widget-smart-heading()
#vp-widget-part()
#pagebreak()
#set page(header: vp-header-theme-03())
= Header 03
#vp-part("Running part")
#vp-widget-stack(vp-widget-author(), vp-widget-school())
#vp-widget-stack(vp-widget-date(), vp-widget-exam(), vp-widget-target())
#vp-widget-heading()
#vp-widget-smart-heading()
#vp-widget-part()
#pagebreak()
#set page(header: vp-header-theme-04())
= Header 04
#vp-part("Running part")
#vp-widget-stack(vp-widget-author(), vp-widget-school())
#vp-widget-stack(vp-widget-date(), vp-widget-exam(), vp-widget-target())
#vp-widget-heading()
#vp-widget-smart-heading()
#vp-widget-part()
#pagebreak()
#set page(header: vp-header-theme-05())
= Header 05
#vp-part("Running part")
#vp-widget-stack(vp-widget-author(), vp-widget-school())
#vp-widget-stack(vp-widget-date(), vp-widget-exam(), vp-widget-target())
#vp-widget-heading()
#vp-widget-smart-heading()
#vp-widget-part()
#pagebreak()
#set page(header: vp-header-theme-06())
= Header 06
#vp-part("Running part")
#vp-widget-stack(vp-widget-author(), vp-widget-school())
#vp-widget-stack(vp-widget-date(), vp-widget-exam(), vp-widget-target())
#vp-widget-heading()
#vp-widget-smart-heading()
#vp-widget-part()
#pagebreak()
#set page(header: vp-header-theme-07())
= Header 07
#vp-part("Running part")
#vp-widget-stack(vp-widget-author(), vp-widget-school())
#vp-widget-stack(vp-widget-date(), vp-widget-exam(), vp-widget-target())
#vp-widget-heading()
#vp-widget-smart-heading()
#vp-widget-part()
#pagebreak()
#set page(header: vp-header-theme-08())
= Header 08
#vp-part("Running part")
#vp-widget-stack(vp-widget-author(), vp-widget-school())
#vp-widget-stack(vp-widget-date(), vp-widget-exam(), vp-widget-target())
#vp-widget-heading()
#vp-widget-smart-heading()
#vp-widget-part()
#pagebreak()
#set page(header: vp-header-theme-09())
= Header 09
#vp-part("Running part")
#vp-widget-stack(vp-widget-author(), vp-widget-school())
#vp-widget-stack(vp-widget-date(), vp-widget-exam(), vp-widget-target())
#vp-widget-heading()
#vp-widget-smart-heading()
#vp-widget-part()
#pagebreak()
#set page(header: vp-header-theme-10())
= Header 10
#vp-part("Running part")
#vp-widget-stack(vp-widget-author(), vp-widget-school())
#vp-widget-stack(vp-widget-date(), vp-widget-exam(), vp-widget-target())
#vp-widget-heading()
#vp-widget-smart-heading()
#vp-widget-part()
#pagebreak()
#set page(header: vp-header-theme-11())
= Header 11
#vp-part("Running part")
#vp-widget-stack(vp-widget-author(), vp-widget-school())
#vp-widget-stack(vp-widget-date(), vp-widget-exam(), vp-widget-target())
#vp-widget-heading()
#vp-widget-smart-heading()
#vp-widget-part()
#pagebreak()
#set page(header: vp-header-theme-12())
= Header 12
#vp-part("Running part")
#vp-widget-stack(vp-widget-author(), vp-widget-school())
#vp-widget-stack(vp-widget-date(), vp-widget-exam(), vp-widget-target())
#vp-widget-heading()
#vp-widget-smart-heading()
#vp-widget-part()
#pagebreak()
#set page(header: vp-header-theme-13())
= Header 13
#vp-part("Running part")
#vp-widget-stack(vp-widget-author(), vp-widget-school())
#vp-widget-stack(vp-widget-date(), vp-widget-exam(), vp-widget-target())
#vp-widget-heading()
#vp-widget-smart-heading()
#vp-widget-part()
#pagebreak()
#set page(header: vp-header-theme-14())
= Header 14
#vp-part("Running part")
#vp-widget-stack(vp-widget-author(), vp-widget-school())
#vp-widget-stack(vp-widget-date(), vp-widget-exam(), vp-widget-target())
#vp-widget-heading()
#vp-widget-smart-heading()
#vp-widget-part()
#pagebreak()
#set page(header: vp-header-theme-15())
= Header 15
#vp-part("Running part")
#vp-widget-stack(vp-widget-author(), vp-widget-school())
#vp-widget-stack(vp-widget-date(), vp-widget-exam(), vp-widget-target())
#vp-widget-heading()
#vp-widget-smart-heading()
#vp-widget-part()
#pagebreak()
#set page(footer: vp-footer-kage-enso())
= vp-footer-kage-enso
#pagebreak()
#set page(footer: vp-footer-kage-brush())
= vp-footer-kage-brush
#pagebreak()
#set page(footer: vp-footer-ninja-enso())
= vp-footer-ninja-enso
#pagebreak()
#set page(footer: vp-manual-footer-standard())
= vp-manual-footer-standard
#pagebreak()
#set page(footer: vp-manual-footer-fancy())
= vp-manual-footer-fancy
#pagebreak()
#set page(header: vp-manual-header-standard())
= vp-manual-header-standard
#pagebreak()
#set page(header: vp-manual-header-logo())
= vp-manual-header-logo
#pagebreak()
#set page(header: vp-manual-header-fancy())
= vp-manual-header-fancy
#pagebreak()
#set page(header: none, footer: none)
#vp-logo()
#vp-logo-colored()
#vp-hockage-logo()
#vp-ninja-scholar-logo()
#vp-icon-ninja-silhouette()
#vp-physics-enso-icon([$F=m a$])
#v(20pt)
#vp-note[Remember this formula: $F=m a$.]
#vp-brush("enso-badge", width: 40pt, height: 30pt)
#vp-brush("enso-grunge", width: 40pt, height: 30pt)
#vp-brush("enso-ring-01", width: 40pt, height: 30pt)
#vp-brush("enso-ring-06", width: 40pt, height: 30pt)
#vp-brush("enso-ring-09", width: 40pt, height: 30pt)
#vp-brush("enso-ring-10", width: 40pt, height: 30pt)
#vp-brush("enso-ring-11", width: 40pt, height: 30pt)
#vp-brush("banner-horizontal", width: 40pt, height: 30pt)
#vp-brush("banner-calligraphy-01", width: 40pt, height: 30pt)
#vp-brush("banner-calligraphy-02", width: 40pt, height: 30pt)
#vp-brush("banner-calligraphy-03", width: 40pt, height: 30pt)
#vp-brush("banner-calligraphy-04", width: 40pt, height: 30pt)
#vp-brush("banner-calligraphy-05", width: 40pt, height: 30pt)
#vp-brush("banner-calligraphy-06", width: 40pt, height: 30pt)
#vp-brush("banner-grunge-01", width: 40pt, height: 30pt)
#vp-brush("banner-grunge-02", width: 40pt, height: 30pt)
#vp-brush("banner-grunge-03", width: 40pt, height: 30pt)
#vp-brush("banner-grunge-04", width: 40pt, height: 30pt)
#vp-brush("banner-grunge-05", width: 40pt, height: 30pt)
#vp-brush("banner-ribbon-01", width: 40pt, height: 30pt)
#vp-brush("banner-ribbon-02", width: 40pt, height: 30pt)
#vp-brush("banner-ribbon-03", width: 40pt, height: 30pt)
#vp-brush("banner-ribbon-04", width: 40pt, height: 30pt)
#vp-brush("banner-ribbon-05", width: 40pt, height: 30pt)
#vp-brush("stroke-dynamic-01", width: 40pt, height: 30pt)
#vp-brush("stroke-dynamic-02", width: 40pt, height: 30pt)
#vp-brush("stroke-curve-01", width: 40pt, height: 30pt)
#vp-brush("stroke-curve-02", width: 40pt, height: 30pt)
#vp-brush("splatter-01", width: 40pt, height: 30pt)
#vp-brush("splatter-02", width: 40pt, height: 30pt)
#vp-brush("splatter-05", width: 40pt, height: 30pt)
#vp-brush("splatter-09", width: 40pt, height: 30pt)
#vp-brush("splatter-10", width: 40pt, height: 30pt)
#vp-brush("splatter-19", width: 40pt, height: 30pt)
#vp-brush("splatter-20", width: 40pt, height: 30pt)
#vp-unit("m/s^2")
#vp-unit("kg*m.s^-1")
#vp-unit("Omega")
#vp-unit("microF")
#vp-unit("degC")
#vp-unit("Angstrom")
#vp-unit("pi")
#vp-unit("um")
#vp-unit("m^0.5")
#vp-unit([$m/s$])
#vp-question([Essay], type: "essay", listEs: none)

